apiVersion: v1
kind: Pod
metadata:
  name: load-generator-pod
spec:
  containers:
  - name: load-generator-ctr
    image: capiedrav/load-generator-img:v1
    env:
      - name: END_POINT
        value: "web-app-service"
      - name: SLEEP_INTERVAL
        value: "0.5"
    resources:      
      limits:
        cpu: "0.5"
        memory: "256Mi"
    